=== raml-apis/FlightStats/schemas/delayindexResourceVersionResponse-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "apiVersion" : {
      "type" : "string" ,
      "required" : false
    } ,
    "swaggerVersion" : {
      "type" : "string" ,
      "required" : false
    } ,
    "basePath" : {
      "type" : "string" ,
      "required" : false
    } ,
    "resourcePath" : {
      "type" : "string" ,
      "required" : false
    } ,
    "apis" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "path" : {
              "type" : "string" ,
              "required" : false
            } ,
            "description" : {
              "type" : "string" ,
              "required" : false
            } ,
            "operations" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
                {
                  "type" : "object" ,
                  "properties" : {
                    "httpMethod" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "summary" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "notes" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "responseClass" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "nickname" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "errorResponses" : {
                      "type" : "array" ,
                      "required" : false ,
                      "items" : [
                        {
                          "type" : "object" ,
                          "properties" : {
                            "code" : {
                              "type" : "number" ,
                              "required" : false
                            } ,
                            "reason" : {
                              "type" : "string" ,
                              "required" : false
                            }
                          }
                        }
                      ]
                    } ,
                    "parameters" : {
                      "type" : "array" ,
                      "required" : false ,
                      "items" : [
                        {
                          "type" : "object" ,
                          "properties" : {
                            "name" : {
                              "type" : "string" ,
                              "required" : false
                            } ,
                            "description" : {
                              "type" : "string" ,
                              "required" : false
                            } ,
                            "paramType" : {
                              "type" : "string" ,
                              "required" : false
                            } ,
                            "required" : {
                              "type" : "boolean" ,
                              "required" : false
                            } ,
                            "allowMultiple" : {
                              "type" : "boolean" ,
                              "required" : false
                            } ,
                            "dataType" : {
                              "type" : "string" ,
                              "required" : false
                            }
                          }
                        } , {
                          "type" : "object" ,
                          "properties" : {
                            "name" : {
                              "type" : "string" ,
                              "required" : false
                            } ,
                            "description" : {
                              "type" : "string" ,
                              "required" : false
                            } ,
                            "paramType" : {
                              "type" : "string" ,
                              "required" : false
                            } ,
                            "defaultValue" : {
                              "type" : "string" ,
                              "required" : false
                            } ,
                            "required" : {
                              "type" : "boolean" ,
                              "required" : false
                            } ,
                            "allowMultiple" : {
                              "type" : "boolean" ,
                              "required" : false
                            } ,
                            "dataType" : {
                              "type" : "string" ,
                              "required" : false
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    } ,
    "models" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "Response" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "properties" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "request" : {
                  "type" : "object" ,
                  "required" : false ,
                  "properties" : {
                    "type" : {
                      "type" : "string" ,
                      "required" : false
                    }
                  }
                } ,
                "error" : {
                  "type" : "object" ,
                  "required" : false ,
                  "properties" : {
                    "type" : {
                      "type" : "string" ,
                      "required" : false
                    }
                  }
                } ,
                "delayIndexes" : {
                  "type" : "object" ,
                  "required" : false ,
                  "properties" : {
                    "items" : {
                      "type" : "object" ,
                      "required" : false ,
                      "properties" : {
                        "$ref" : {
                          "type" : "string" ,
                          "required" : false
                        }
                      }
                    } ,
                    "type" : {
                      "type" : "string" ,
                      "required" : false
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== raml-apis/FlightStats/examples/delayindexResourceVersionResponse-example.json
{
  "apiVersion" : "0.0.0" ,
  "swaggerVersion" : "1.0" ,
  "basePath" : "https://api.flightstats.com/flex/delayindex/rest" ,
  "resourcePath" : "/v1/json/" ,
  "apis" : [
    {
      "path" : "/v1/json/country/{country}" ,
      "description" : "DelayIndex API returning results in JSON format" ,
      "operations" : [
        {
          "httpMethod" : "GET" ,
          "summary" : "Delay Indexes by Country code" ,
          "notes" : "Returns DelayIndexes for airports in the given Country" ,
          "responseClass" : "response" ,
          "nickname" : "forCountry" ,
          "errorResponses" : [
            {
              "code" : 400 ,
              "reason" : "Client request error. Consult error response for specifics."
            } , {
              "code" : 403 ,
              "reason" : "Authorization failure. Invalid 'appId', 'appKey', or rate limit violation."
            } , {
              "code" : 404 ,
              "reason" : "Resource not found. Request did not match a URL for the service."
            } , {
              "code" : 500 ,
              "reason" : "Service error. Consult error response for specifics."
            }
          ] ,
          "parameters" : [
            {
              "name" : "appId" ,
              "description" : "Application ID" ,
              "paramType" : "query" ,
              "required" : true ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "appKey" ,
              "description" : "Application key" ,
              "paramType" : "query" ,
              "required" : true ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "country" ,
              "description" : "Country code (2 character)" ,
              "paramType" : "path" ,
              "required" : true ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "classification" ,
              "description" : "Airport classification filter, used to restrict results to larger airports [1-5, 1=largest]" ,
              "paramType" : "query" ,
              "defaultValue" : "5" ,
              "required" : false ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "score" ,
              "description" : "Delay index normalized score filter, used to restrict results to airports experiencing delays [0-5, 5=maximum delay]" ,
              "paramType" : "query" ,
              "defaultValue" : "3" ,
              "required" : false ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "extendedOptions" ,
              "description" : "Extended options for modifying standard API behavior to fit special use cases.  Options: 'useInlinedReferences', 'useHttpErrors'." ,
              "paramType" : "query" ,
              "required" : false ,
              "allowMultiple" : false ,
              "dataType" : "string"
            }
          ]
        }
      ]
    } , {
      "path" : "/v1/json/region/{region}" ,
      "description" : "DelayIndex API returning results in JSON format" ,
      "operations" : [
        {
          "httpMethod" : "GET" ,
          "summary" : "Delay Indexes by Region" ,
          "notes" : "Returns DelayIndexes for airports in the given Region" ,
          "responseClass" : "response" ,
          "nickname" : "forRegion" ,
          "errorResponses" : [
            {
              "code" : 400 ,
              "reason" : "Client request error. Consult error response for specifics."
            } , {
              "code" : 403 ,
              "reason" : "Authorization failure. Invalid 'appId', 'appKey', or rate limit violation."
            } , {
              "code" : 404 ,
              "reason" : "Resource not found. Request did not match a URL for the service."
            } , {
              "code" : 500 ,
              "reason" : "Service error. Consult error response for specifics."
            }
          ] ,
          "parameters" : [
            {
              "name" : "appId" ,
              "description" : "Application ID" ,
              "paramType" : "query" ,
              "required" : true ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "appKey" ,
              "description" : "Application key" ,
              "paramType" : "query" ,
              "required" : true ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "region" ,
              "description" : "Region [Africa, Antarctica, Asia, Caribbean, Central-America, Europe, Middle-East, North-America, Oceania, South-America]" ,
              "paramType" : "path" ,
              "required" : true ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "classification" ,
              "description" : "Airport classification filter, used to restrict results to larger airports [1-5, 1=largest]" ,
              "paramType" : "query" ,
              "defaultValue" : "5" ,
              "required" : false ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "score" ,
              "description" : "Delay index normalized score filter, used to restrict results to airports experiencing delays [0-5, 5=maximum delay]" ,
              "paramType" : "query" ,
              "defaultValue" : "3" ,
              "required" : false ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "extendedOptions" ,
              "description" : "Extended options for modifying standard API behavior to fit special use cases.  Options: 'useInlinedReferences', 'useHttpErrors'." ,
              "paramType" : "query" ,
              "required" : false ,
              "allowMultiple" : false ,
              "dataType" : "string"
            }
          ]
        }
      ]
    } , {
      "path" : "/v1/json/state/{state}" ,
      "description" : "DelayIndex API returning results in JSON format" ,
      "operations" : [
        {
          "httpMethod" : "GET" ,
          "summary" : "Delay Indexes by State code (US and Canada only)" ,
          "notes" : "Returns DelayIndexes for airports in the given State" ,
          "responseClass" : "response" ,
          "nickname" : "forState" ,
          "errorResponses" : [
            {
              "code" : 400 ,
              "reason" : "Client request error. Consult error response for specifics."
            } , {
              "code" : 403 ,
              "reason" : "Authorization failure. Invalid 'appId', 'appKey', or rate limit violation."
            } , {
              "code" : 404 ,
              "reason" : "Resource not found. Request did not match a URL for the service."
            } , {
              "code" : 500 ,
              "reason" : "Service error. Consult error response for specifics."
            }
          ] ,
          "parameters" : [
            {
              "name" : "appId" ,
              "description" : "Application ID" ,
              "paramType" : "query" ,
              "required" : true ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "appKey" ,
              "description" : "Application key" ,
              "paramType" : "query" ,
              "required" : true ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "state" ,
              "description" : "State code (2 character)" ,
              "paramType" : "path" ,
              "required" : true ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "classification" ,
              "description" : "Airport classification filter, used to restrict results to larger airports [1-5, 1=largest]" ,
              "paramType" : "query" ,
              "defaultValue" : "5" ,
              "required" : false ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "score" ,
              "description" : "Delay index normalized score filter, used to restrict results to airports experiencing delays [0-5, 5=maximum delay]" ,
              "paramType" : "query" ,
              "defaultValue" : "3" ,
              "required" : false ,
              "allowMultiple" : false ,
              "dataType" : "string"
            } , {
              "name" : "extendedOptions" ,
              "description" : "Extended options for modifying standard API behavior to fit special use cases.  Options: 'useInlinedReferences', 'useHttpErrors'." ,
              "paramType" : "query" ,
              "required" : false ,
              "allowMultiple" : false ,
              "dataType" : "string"
            }
          ]
        }
      ]
    } , {
      "path" : "/v1/json/airports/{airports}" ,
      "description" : "DelayIndex API returning results in JSON format" ,
      "operations" : [
        {
          "httpMethod" : "GET" ,
          "summary" : "Delay Indexes by Airport" ,
          "notes" : "Returns the current DelayIndex(es) for the given Airport(s)" ,
          "responseClass" : "response" ,
          "nickname" : "forAirport" ,
          "errorResponses" : [
            {
              "code" : 400 ,
              "reason" : "Client request error. Consult error response for specifics."
            } , {
              "code" : 403 ,
              "reason" : "Authorization failure. Invalid 'appId', 'appKey', or rate limit violation."
            } , {
              "code" : 404 ,
