=== raml-apis/FlightStats/schemas/departingMonitoringJSONResponse-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "request" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "airport" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "requestedCode" : {
              "type" : "string" ,
              "required" : false
            } ,
            "fsCode" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "url" : {
          "type" : "string" ,
          "required" : false
        } ,
        "airlineCode" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "requestedCode" : {
              "type" : "string" ,
              "required" : false
            } ,
            "fsCode" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "flightNumber" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "requested" : {
              "type" : "string" ,
              "required" : false
            } ,
            "interpreted" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "date" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "year" : {
              "type" : "string" ,
              "required" : false
            } ,
            "month" : {
              "type" : "string" ,
              "required" : false
            } ,
            "day" : {
              "type" : "string" ,
              "required" : false
            } ,
            "interpreted" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "name" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "interpreted" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "description" : {
          "type" : "object" ,
          "required" : false
        } ,
        "type" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "requested" : {
              "type" : "string" ,
              "required" : false
            } ,
            "interpreted" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "deliverTo" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "requested" : {
              "type" : "string" ,
              "required" : false
            } ,
            "interpreted" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "events" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "interpreted" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          ]
        } ,
        "nameValues" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
          ]
        } ,
        "codeType" : {
          "type" : "object" ,
          "required" : false
        } ,
        "extendedOptions" : {
          "type" : "object" ,
          "required" : false
        }
      }
    } ,
    "rule" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "id" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "carrierFsCode" : {
          "type" : "string" ,
          "required" : false
        } ,
        "flightNumber" : {
          "type" : "string" ,
          "required" : false
        } ,
        "departureAirportFsCode" : {
          "type" : "string" ,
          "required" : false
        } ,
        "arrivalAirportFsCode" : {
          "type" : "string" ,
          "required" : false
        } ,
        "departure" : {
          "type" : "string" ,
          "required" : false
        } ,
        "arrival" : {
          "type" : "string" ,
          "required" : false
        } ,
        "ruleEvents" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "type" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          ]
        } ,
        "nameValues" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
          ]
        } ,
        "delivery" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "format" : {
              "type" : "string" ,
              "required" : false
            } ,
            "destination" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      }
    } ,
    "appendix" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "airlines" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "fs" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "iata" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "icao" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "name" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "phoneNumber" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "active" : {
                  "type" : "boolean" ,
                  "required" : false
                }
              }
            }
          ]
        } ,
        "airports" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "fs" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "iata" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "icao" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "faa" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "name" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "street1" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "city" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "cityCode" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "stateCode" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "postalCode" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "countryCode" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "countryName" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "regionName" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "timeZoneRegionName" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "weatherZone" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "localTime" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "utcOffsetHours" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "latitude" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "longitude" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "elevationFeet" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "classification" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "active" : {
                  "type" : "boolean" ,
                  "required" : false
                }
              }
            } , {
              "type" : "object" ,
              "properties" : {
                "fs" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "iata" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "icao" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "faa" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "name" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "street1" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "street2" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "city" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "cityCode" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "stateCode" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "postalCode" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "countryCode" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "countryName" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "regionName" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "timeZoneRegionName" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "weatherZone" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "localTime" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "utcOffsetHours" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "latitude" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "longitude" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "elevationFeet" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "classification" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "active" : {
                  "type" : "boolean" ,
                  "required" : false
                }
              }
            }
          ]
        }
      }
    } ,
    "alertCapabilities" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "baggage" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "departureGateChange" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "arrivalGateChange" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "gateDeparture" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "gateArrival" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "runwayDeparture" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "runwayArrival" : {
          "type" : "boolean" ,
          "required" : false
        }
      }
    }
  }
}

=== raml-apis/FlightStats/examples/arrivingAirportMonitoringJSONResponse-example.json
{
  "request" : {
    "airport" : {
      "requestedCode" : "ORD" ,
      "fsCode" : "ORD"
    } ,
    "url" : "https://api.flightstats.com/flex/alerts/rest/v1/json/create/AA/1113/to/ORD/arriving/2015/5/2" ,
    "airlineCode" : {
      "requestedCode" : "AA" ,
      "fsCode" : "AA"
    } ,
    "flightNumber" : {
      "requested" : "1113" ,
      "interpreted" : "1113"
    } ,
    "date" : {
      "year" : "2015" ,
      "month" : "5" ,
      "day" : "2" ,
      "interpreted" : "2015-05-02"
    } ,
    "name" : {
      "interpreted" : "Default"
    } ,
    "description" : {
    } ,
    "type" : {
      "requested" : "json" ,
      "interpreted" : "JSON"
    } ,
    "deliverTo" : {
      "requested" : "your@email.com" ,
      "interpreted" : "your@email.com"
    } ,
    "events" : [
      {
        "interpreted" : "all"
      }
    ] ,
    "nameValues" : [
    ] ,
    "codeType" : {
    } ,
    "extendedOptions" : {
    }
  } ,
  "rule" : {
    "id" : "264822106" ,
    "name" : "Default" ,
    "carrierFsCode" : "AA" ,
    "flightNumber" : "1113" ,
    "departureAirportFsCode" : "LAX" ,
    "arrivalAirportFsCode" : "ORD" ,
    "departure" : "2015-05-02T01:30:00.000" ,
    "arrival" : "2015-05-02T07:38:00.000" ,
    "ruleEvents" : [
      {
        "type" : "ALL_CHANGES"
      }
    ] ,
    "nameValues" : [
    ] ,
    "delivery" : {
      "format" : "json" ,
      "destination" : "your@email.com"
    }
  } ,
  "appendix" : {
    "airlines" : [
      {
        "fs" : "AA" ,
        "iata" : "AA" ,
        "icao" : "AAL" ,
        "name" : "American Airlines" ,
        "phoneNumber" : "1-800-433-7300" ,
        "active" : true
      }
    ] ,
    "airports" : [
      {
        "fs" : "ORD" ,
        "iata" : "ORD" ,
        "icao" : "KORD" ,
        "faa" : "ORD" ,
        "name" : "O'Hare International Airport" ,
        "street1" : "10000 West O'Hare" ,
        "city" : "Chicago" ,
        "cityCode" : "CHI" ,
        "stateCode" : "IL" ,
        "postalCode" : "60666" ,
        "countryCode" : "US" ,
        "countryName" : "United States" ,
        "regionName" : "North America" ,
        "timeZoneRegionName" : "America/Chicago" ,
        "weatherZone" : "ILZ014" ,
        "localTime" : "2015-04-27T21:58:59.367" ,
        "utcOffsetHours" : -5 ,
        "latitude" : 41.976912 ,
        "longitude" : -87.904876 ,
        "elevationFeet" : 668 ,
        "classification" : 1 ,
        "active" : true
      } , {
        "fs" : "LAX" ,
        "iata" : "LAX" ,
        "icao" : "KLAX" ,
        "faa" : "LAX" ,
        "name" : "Los Angeles International Airport" ,
        "street1" : "One World Way" ,
        "street2" : "" ,
        "city" : "Los Angeles" ,
        "cityCode" : "LAX" ,
        "stateCode" : "CA" ,
        "postalCode" : "90045-5803" ,
        "countryCode" : "US" ,
        "countryName" : "United States" ,
        "regionName" : "North America" ,
        "timeZoneRegionName" : "America/Los_Angeles" ,
        "weatherZone" : "CAZ041" ,
        "localTime" : "2015-04-27T19:59:00.052" ,
        "utcOffsetHours" : -7 ,
        "latitude" : 33.943399 ,
        "longitude" : -118.408279 ,
        "elevationFeet" : 126 ,
        "classification" : 1 ,
        "active" : true
      }
    ]
  } ,
  "alertCapabilities" : {
    "baggage" : true ,
    "departureGateChange" : true ,
    "arrivalGateChange" : true ,
    "gateDeparture" : true ,
    "gateArrival" : true ,
    "runwayDeparture" : true ,
    "runwayArrival" : true
  }
}
